import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Building2, MapPin, Users, Search, Plus, Trash2, Edit2, Grid, List } from 'lucide-react';
import { useAppStore } from '../store/useAppStore';
import { useAuthStore } from '../store/useAuthStore';
import { Card, CardHeader, CardTitle, CardFooter } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Badge } from '../components/ui/Badge';
export const ResourcesPage = () => {
    const { resources, loadingStates } = useAppStore();
    const { user } = useAuthStore();
    const [searchTerm, setSearchTerm] = useState('');
    const [viewMode, setViewMode] = useState('grid');
    const isAdmin = user?.role === 'ADMIN';
    const filteredResources = resources.filter(r => r.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        r.location.toLowerCase().includes(searchTerm.toLowerCase()));
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "flex flex-col md:flex-row md:items-center justify-between gap-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold tracking-tight", children: "Resource Registry" }), _jsx("p", { className: "text-muted-foreground mt-1", children: "Browse and manage all campus facilities and equipment." })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "flex bg-accent/30 p-1 rounded-lg mr-2", children: [_jsx(Button, { variant: viewMode === 'grid' ? 'secondary' : 'ghost', size: "icon", className: "h-8 w-8", onClick: () => setViewMode('grid'), children: _jsx(Grid, { className: "w-4 h-4" }) }), _jsx(Button, { variant: viewMode === 'list' ? 'secondary' : 'ghost', size: "icon", className: "h-8 w-8", onClick: () => setViewMode('list'), children: _jsx(List, { className: "w-4 h-4" }) })] }), isAdmin && (_jsxs(Button, { className: "gap-2", children: [_jsx(Plus, { className: "w-4 h-4" }), " Add Resource"] }))] })] }), _jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" }), _jsx(Input, { className: "pl-10 h-12", placeholder: "Search by name, type, or building...", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value) })] }), loadingStates.resources === 'loading' ? (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: [1, 2, 3, 4, 5, 6].map(i => (_jsx("div", { className: "h-64 rounded-2xl bg-accent/20 animate-pulse border border-border" }, i))) })) : (_jsxs("div", { className: viewMode === 'grid'
                    ? "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
                    : "space-y-4", children: [filteredResources.map((resource) => (_jsxs(Card, { className: "group hover:border-primary/50 transition-all overflow-hidden flex flex-col", children: [_jsxs("div", { className: "h-24 bg-gradient-to-br from-primary/10 to-accent/20 flex items-center justify-center relative", children: [_jsx("div", { className: "absolute top-4 right-4 flex gap-2", children: _jsx(Badge, { variant: "secondary", className: "bg-background/80 backdrop-blur-md", children: resource.type }) }), _jsx("div", { className: "w-12 h-12 rounded-xl bg-background flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform", children: _jsx(Building2, { className: "text-primary w-6 h-6" }) })] }), _jsxs(CardHeader, { className: "flex-1", children: [_jsx(CardTitle, { children: resource.name }), _jsxs("div", { className: "flex items-center gap-2 text-sm text-muted-foreground mt-2", children: [_jsx(MapPin, { className: "w-3.5 h-3.5" }), " ", resource.location] }), _jsxs("div", { className: "flex items-center gap-2 text-sm text-muted-foreground mt-1", children: [_jsx(Users, { className: "w-3.5 h-3.5" }), " Capacity: ", resource.capacity, " people"] })] }), _jsxs(CardFooter, { className: "bg-accent/10 border-t border-border flex justify-between", children: [_jsx(Button, { variant: "ghost", size: "sm", className: "text-xs group-hover:text-primary", children: "View Availability" }), isAdmin && (_jsxs("div", { className: "flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity", children: [_jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8", children: _jsx(Edit2, { className: "w-3.5 h-3.5" }) }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 text-destructive", children: _jsx(Trash2, { className: "w-3.5 h-3.5" }) })] }))] })] }, resource.id))), filteredResources.length === 0 && (_jsxs("div", { className: "col-span-full py-32 text-center", children: [_jsx(Building2, { className: "w-16 h-16 text-muted-foreground/20 mx-auto mb-4" }), _jsx("h3", { className: "text-xl font-bold", children: "No Resources Found" }), _jsx("p", { className: "text-muted-foreground", children: "Adjust your search or add a new resource." })] }))] }))] }));
};
